# Generated by Django 4.1 on 2022-10-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pojistenec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=20, verbose_name='Jméno')),
                ('datum_narozeni', models.DateTimeField(verbose_name='Datum narození')),
            ],
        ),
    ]
