# Generated by Django 4.1 on 2022-10-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprava', '0002_rename_pojistenec_uivatel_alter_uivatel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=20, verbose_name='Jméno')),
                ('datum_narozeni', models.DateField(verbose_name='Datum narození')),
            ],
            options={
                'verbose_name': 'Uživatel',
                'verbose_name_plural': 'Uživatelé',
            },
        ),
        migrations.DeleteModel(
            name='Uivatel',
        ),
    ]
