# Generated by Django 4.1 on 2022-10-09 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprava', '0003_uzivatel_delete_uivatel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('obsah', models.TextField()),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprava.uzivatel', verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Komentář',
                'verbose_name_plural': 'Komentáře',
            },
        ),
    ]
